coffepoint/accounting/urls.py
from django.urls import path

from .views import AccountungView, UserView

urlpatterns = [
    path('accounting/', AccountungView.as_view(), name='index'),
    path('accounting/users/<owner_name>/', UserView.as_view(), name='users'),
]

coffepoint/coffepoint/urls.py
# from django.contrib import admin
# from django.views.generic import RedirectView
from django.urls import path, include  # , re_path
# from .urls import urlpatterns

urlpatterns = [
    # re_path(r'^favicon\.ico$', RedirectView.as_view(url='/static/images/favicon.ico')),
    path('', include(('accounting.urls', 'accounting'), namespace='accounting')),
    # path('', include((urlpatterns, 'accounting'))),
    # path('admin/', admin.site.urls),
]

coffepoint/accounting/models.py
from django.db import models
from django.contrib.auth.models import User


class Shelf(models.Model):
    id = models.IntegerField(primary_key=True, unique=True)
    number = models.CharField(max_length=32)

    class Meta:
        app_label = 'accounting'


class Cup(models.Model):
    """
    Если удаляем юзера, то кружка останется.
    Если удаляем полку, то кружки удаляются.
    """
    id = models.IntegerField(primary_key=True, unique=True)
    owner = models.ForeignKey(User, null=True, db_index=True, on_delete=models.SET_NULL, db_column='owner_id')
    shelf = models.ForeignKey(Shelf, db_index=True, on_delete=models.CASCADE, db_column='shelf_id')
    volume = models.IntegerField()

    class Meta:
        app_label = 'accounting'

    def __str__(self):
        return f'{self.volume} мл.'


class Material(models.Model):
    id = models.IntegerField(primary_key=True, unique=True)
    title = models.CharField(max_length=124)


class CupMaterials(models.Model):
    # Нельзя удалить материал, если есть кружки из него
    # Если кружка удаляется, то связь с материалом тоже удаляется, т.к. в ней не будет смысла и может породить баги
    id = models.IntegerField(primary_key=True, unique=True)
    material = models.ForeignKey(Material, db_index=True, on_delete=models.PROTECT, db_column='material_id')
    cup = models.ForeignKey(Cup, null=True, db_index=True, on_delete=models.CASCADE, db_column='cup_id')

    class Meta:
        db_table = 'accounting_cup_materials'
        app_label = 'accounting'

coffepoint/accounting/views.py
from collections import defaultdict
from django.views.generic import TemplateView, DetailView
from django.db.models.functions import Replace
from django.db.models import Value
from django.shortcuts import get_object_or_404

from .models import User, CupMaterials


class CupData:
    def __init__(self):
        self.owner_name = None

    def get_shelves(self) -> dict:
        """
        Группируем чашки по полкам, определяем состав чашек.
        Чашки заведенные в БД без связи с материалами не будут отображаться, т.к. от идем от CupMaterials (надо ли?)
        :return: dict
        """
        query = CupMaterials.objects.select_related('cup', 'material')
        if self.owner_name:
            query = query.filter(cup__owner__username=self.owner_name)
        query = query.all()
        selves = defaultdict(dict)
        cup_materials = defaultdict(list)
        for raw in query:
            cup_id = raw.cup.id
            shelf_name = raw.cup.shelf.number
            cup_materials[cup_id].append(raw.material.title)
            cup_data = {'cup_id': raw.cup.id,
                        'owner_name': raw.cup.owner.username if raw.cup.owner else None,
                        'shelf_name': raw.cup.shelf.number,
                        'cup_volume': raw.cup,
                        }
            selves[shelf_name][cup_id] = cup_data
        for shelf_data in selves.values():
            for cup_id, cup_data in shelf_data.items():
                cup_data['owner_name'] = cup_data['owner_name'].replace(' ', '') \
                    if cup_data['owner_name'] else None
                cup_data['materials'] = sorted(cup_materials.get(cup_id, []))
        return dict(selves)


class AccountungView(TemplateView, CupData):
    template_name = "index.html"

    def __init__(self):
        CupData.__init__(self)
        self.context = None

    def get_context_data(self):
        shelves = self.get_shelves()
        self.context = {'shelves': shelves, 'owner_name': None}
        return self.context


class UserView(DetailView, CupData):
    template_name = "user.html"
    model = User

    def __init__(self):
        CupData.__init__(self)
        self.context = None

    def get_object(self, **kwargs):
        # Все replace из-за юзера "mr. Zolp"
        user = get_object_or_404(User.objects.annotate(owner_name=Replace('username',
                                                                          Value(' '),
                                                                          Value(''))
                                                       ),
                                 owner_name=self.kwargs['owner_name'])
        self.owner_name = user.username
        shelves = self.get_shelves()
        self.context = {'shelves': shelves, 'owner_name': user.username}

    def get_context_data(self, **kwargs):
        return self.context

coffepoint/accounting/templates/_cup_table.html
<table>
    <tbody>
        {% if enable_head %}
            <h3>Полка {{ shelf }}</h3>
            <tr align="left">
                <td><b>ID</b></td>
                <td><b>Владелец</b></td>
                <td><b>Объем</b></td>
                <td><b>Материалы</b></td>
            </tr>
        {% elif not enable_head and not step %}
            <tr align="left">
                <td><b>ID</b></td>
                <td><b>Владелец</b></td>
                <td><b>Объем</b></td>
                <td><b>Материалы</b></td>
            </tr>
        {% endif %}
        {% for cup in cups.values %}
            <tr align="left">
                <td>{{ cup.cup_id }}</td>
                {% if cup.owner_name %}
                    <td><a href="{% url 'accounting:users' owner_name=cup.owner_name %}">{{ cup.owner_name }}</a></td>
                {% else %}
                    <td>общая</td>
                {% endif %}
                <td>{{ cup.cup_volume }}</td>
                <td>
                    {% for material in cup.materials %}
                        {{ material }}{% if not forloop.last %}, {% else %}{% endif %}
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

coffepoint/accounting/templates/base.html
<html>
<body>
{% block content %}
{% endblock content %}
</body>
</html>

coffepoint/accounting/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>На корабле SpaceX-2187 известно о следующих чашках</h1>

{% if shelves %}
    {% for shelf_name, cups in shelves.items %}
        {% include "_cup_table.html" with shelf=shelf_name cups=cups enable_head=1 step=0 only%}
    {% endfor %}
{% else %}
    <p>На корабле нет полочек :C</p>
{% endif %}

{% endblock content %}

coffepoint/accounting/templates/user.html
{% extends "base.html" %}

{% block content %}
<h1>Космонавт {{ owner_name }} принёс на борт следующие чашки</h1>

{% if shelves %}
    {% for shelf_name, cups in shelves.items %}
        {% include "_cup_table.html" with shelf=shelf_name cups=cups enable_head=0 step=forloop.counter0 only%}
    {% endfor %}
{% else %}
    <p>Ничего {{ owner_name }} не принес, но должен был</p>
{% endif %}

{% endblock content %}